# MH-Weed16 Version 1 class map.
# Use this as a reference for dataset conversion and reporting.
names:
  0: Kena
  1: Lavhala
  2: Lambs_Quarter_Plant
  3: Little_Mallow
  4: Moti_dudhi
  5: Obscure_morning_glory
  6: Asian_pigeon_wings
  7: Bilayat
  8: Choti_dudhi
  9: Digitaria_SP
  10: Gajar_gavat
  11: Graceful_sandmat
  12: Sicklepod
  13: Harali
  14: Dwarf_cassia
  15: Punarnava
