# MH-Weed16 Version 1
#
# Current project model:
# 15-class subset used for the prepared YOLO dataset.
#
# Punarnava (class 15) is part of the original MH-Weed16 dataset
# but is not included in the current prepared training dataset.

dataset:
  source: MH-Weed16
  version: 1
  implemented_classes: 15

names:
  0: Kena
  1: Lavhala
  2: Lambs_Quarter_Plant
  3: Little_Mallow
  4: Moti_dudhi
  5: Obscure_morning_glory
  6: Asian_pigeon_wings
  7: Bilayat
  8: Choti_dudhi
  9: Digitaria_SP
  10: Gajar_gavat
  11: Graceful_sandmat
  12: Sicklepod
  13: Harali
  14: Dwarf_cassia
